apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: argocd-git-repo-generator-function
spec:
  package: xpkg.upbound.io/benmbarekachref/argocd-git-repo-generator-function:v0.0.0-9d4ddded1763
