apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: argocd-composition
spec:
  compositeTypeRef:
    apiVersion: what-is-it-that-you-truly-desire.org/v1alpha1
    kind: xMyArgoCd
  mode: Pipeline
  pipeline:
    - step: argo-repo-generator
      functionRef:
        name: argocd-git-repo-generator-function
      input:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: argocd
        spec:
          forProvider:
            chart:
              name: argo-cd
              repository: https://argoproj.github.io/argo-helm
              version: 7.7.10
            namespace: argocd
            values:
              server: 
                service:
                  type: ClusterIP
                ingress: 
                  enabled: true
                  ingressClassName: "nginx"
                  hostname: "argocd.local"
                  path: /
                  pathType: Prefix
                  tls: false
                 # tls: true
                 # annotation:
                 #   cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
                extraArgs:
                  - --insecure
              configs:
                secret:
                  createSecret: true
                  argocdServerAdminPassword: "$2b$12$8z/N/HakTkOAiGnA4y7aGuVrlEvzierbqFuM9b0eL9EgX51ylQDWq" 
    - step: check-function-resource-readiness
      functionRef:
        name: upbound-function-auto-ready

